# Cloudflare Tunnel Configuration for Influmojo Development
# This file is a template that gets copied to ~/.cloudflared/config.yml by setup scripts
# The actual credentials (influmojo-dev.json) are generated separately and NOT in this repo

tunnel: influmojo-dev
credentials-file: ~/.cloudflared/influmojo-dev.json

ingress:
  # API Backend (Express.js server)
  - hostname: api.influmojo.in
    service: http://localhost:3002
  
  # Frontend/Web App (if you have one)
  - hostname: dev.influmojo.in
    service: http://localhost:3000
  
  # Webhook Receiver (for Zoho, Stripe, etc.)
  - hostname: webhook.influmojo.in
    service: http://localhost:3002
  
  # OAuth Callback Handler
  - hostname: auth.influmojo.in
    service: http://localhost:3002
  
  # Chat Integration (Zoho SalesIQ)
  - hostname: chat.influmojo.in
    service: http://localhost:3002
  
  # Health Check
  - hostname: health.influmojo.in
    service: http://localhost:3002
  
  # Catch-all for unmatched hostnames
  - service: http_status:404 